name: mm_template
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  core:
    path: packages/core
  authorization:
    path: packages/authorization
  profile:
    path: packages/profile
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  easy_localization: ^3.0.7
  easy_logger: ^0.0.2
  get_it: ^7.6.4
  injectable: ^2.3.2
  logging: ^1.2.0
  go_router: ^13.0.1
  equatable: ^2.0.5
  freezed_annotation: ^2.4.1
  cupertino_icons: ^1.0.6
  auto_route: ^8.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_gen_runner: ^5.3.2
  build_runner: ^2.4.7
  injectable_generator: ^2.4.1
  go_router_builder: ^2.4.1
  flutter_lints: ^2.0.0
  intl: ^0.19.0
  melos: ^3.4.0
  freezed: ^2.4.6
  auto_route_generator: ^8.1.0

flutter_gen:
  output: lib/generated/

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
