name: {{name.snakeCase()}}
description: {{description}}
version: 0.0.1
repository: https://gitlab.platform.corp/kazanexpress/mm-flutter-platform/packages/{{name.snakeCase()}}
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.17.0"

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  build_runner: ^2.4.7
  mm_flutter_linter:
    git:
      url: git@gitlab.platform.corp:kazanexpress/mm-flutter-platform.git
      path: packages/mm_flutter_linter
